modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]]
modId="minestar"
version="0.1"
displayName="MineStar Mod"
logoFile="minestar.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
'''

[[dependencies.minestar]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minestar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
